image: node:10.10.0

cache:
  paths:
    - node_modules/

before_script:
  - npm ci

test_async:
  script:
    - npm run test
  only:
    - staging

pages:
  only:
    - master
  stage: deploy
  script:
    - npm run docs:build
  artifacts:
    paths:
      - public
