# Copyright 2020 Edouard Maleix, read LICENSE

# include:
# template: Dependency-Scanning.gitlab-ci.yml

cache:
  paths:
    - node_modules/

stages:
  - build
  - test
  - deploy
  - .post

variables:
  NODE_ENV: 'development'
  NODE_NAME: 'device-manager'
  ALOES_ID: '9e35aae4-c8c5-11e9-a32f-51ba8653'
  ALOES_KEY: '9a742eca81ba99ac826d3a7cc766f1ce94a321b0'
  ADMIN_EMAIL: 'ed@getlarge.eu'
  CONTACT_EMAIL: 'hey@getlarge.eu'
  DOMAIN: 'localhost'
  HTTP_SERVER_URL: 'http://0.0.0.0:8000'
  HTTP_CLIENT_URL: 'http://0.0.0.0:8080'
  HTTP_SERVER_HOST: '0.0.0.0'
  HTTP_SERVER_PORT: '8000'
  HTTP_TRUST_PROXY: 'true'
  REST_API_ROOT: '/api'
  COOKIE_SECRET: '246bace2-38cb-4138-85d9'
  MQTT_BROKER_URL: 'mqtt://0.0.0.0:1883'
  MQTT_BROKER_PORT: '1883'
  MQTT_TRUST_PROXY: 'true'
  WS_BROKER_PORT: '3000'
  SERVER_LOGGER_LEVEL: '2'
  # SMTP_HOST: ''
  SMTP_PORT: '465'
  SMTP_SECURE: 'true'
  # SMTP_USER: ''
  # SMTP_PASS: ''
  INFLUXDB_ADMIN_ENABLED: 'false'
  INFLUXDB_PROTOCOL: 'http'
  INFLUXDB_HOST: 'influxdb'
  INFLUXDB_PORT: '8086'
  INFLUXDB_DB: 'aloes_test'
  INFLUXDB_USER: 'aloes'
  INFLUXDB_USER_PASSWORD: 'example'
  # OCD_API_KEY: ''
  FS_PATH: '../storage'
  GITHUB_CLIENT_ID_LOGIN: ''
  GITHUB_CLIENT_SECRET_LOGIN: ''
  GITHUB_CLIENT_ID_LINK: ''
  GITHUB_CLIENT_SECRET_LINK: ''
  GIT_REPO_SSH_URL: 'git@framagit.org:aloes/device-manager.git'
  INSTANCES_COUNT: '1'
  FF_NETWORK_PER_BUILD: 1
  # DEBUG: 'skyring:*'
  channel__host: 'timer-1'
  nats__hosts: 'nats:4222'
  seeds: 'timer-1:3455'
  storage__backend: 'leveldown'
  storage__path: '/var/data/skyring'

# services:
#   - name: influxdb:1.7-alpine
#     alias: influxdb
#   - name: nats:latest
#     alias: nats
#   - name: quay.io/esatterwhite/skyring
#     alias: timer-1

image: node:12.10.0

prepare:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build:test
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test_async:
  services:
    - name: influxdb:1.7-alpine
      alias: influxdb
    - name: nats:latest
      alias: nats
    - name: quay.io/esatterwhite/skyring
      alias: timer-1
  variables:
    NODE_ENV: 'development'
    CI: 'true'
  script:
    - npm ci
    - npm run test:cover
  artifacts:
    paths:
      - coverage

pages:
  stage: deploy
  dependencies:
    - test_async
  script:
    - npm run docs:build
    - cp -r coverage/* public/
  artifacts:
    paths:
      - public
  only:
    - master
    - staging

publish:
  stage: .post
  script:
    - curl --request POST https://hub.docker.com/api/build/v1/source/$ASYNC_API_DOCKER_REPO/trigger/accd237c-3aa5-4628-96df-7f19aa07d396/call/
    - curl --request POST https://hub.docker.com/api/build/v1/source/$REST_API_DOCKER_REPO/trigger/5d376923-84b9-41f5-a3b8-c9c1d2d24d03/call/
  only:
    - master
