version: '3.7'

services:
  influxdb:
    env_file: ./config/influx/.env
    image: influxdb:1.7-alpine
    volumes:
      - influxvolume:/var/lib/influxdb

  api:
    # env_file: .env
    environment:
      - CI=true
      - NODE_ENV=development
      - NODE_NAME=device-manager
      - ALOES_ID=9e35aae4-c8c5-11e9-a32f-51ba8653
      - ALOES_KEY=9a742eca81ba99ac826d3a7cc766f1ce94a321b0
      - ADMIN_EMAIL=ed@getlarge.eu
      - CONTACT_EMAIL=hey@getlarge.eu
      - DOMAIN=ed-X510URR
      - HTTP_SERVER_URL=http://0.0.0.0:8000
      - HTTP_CLIENT_URL=http://ed-X510URR:8080
      - HTTP_SERVER_HOST=0.0.0.0
      - HTTP_SERVER_PORT=8000
      - HTTP_SECURE=
      - REST_API_ROOT=/api
      - COOKIE_SECRET=246bace2-38cb-1954-2481-ebc12531
      - MQTT_BROKER_URL=mqtt://0.0.0.0:1883
      - MQTT_BROKER_PORT=1883
      - WS_BROKER_PORT=3000
      - SERVER_LOGGER_LEVEL=4
      - SMTP_HOST=
      - SMTP_PORT=465
      - SMTP_SECURE=
      - SMTP_USER=
      - SMTP_PASS=
      - INFLUX_PROTOCOL=http
      - INFLUX_HOST=influxdb
      - INFLUX_PORT=8086
      - INFLUX_COLLECTION=aloes_test
      - INFLUX_USER=aloes
      - INFLUX_PASS=example
      - OCD_API_KEY=682b827b96294325a99e344b4466923b
      - FS_PATH=./storage
      # - GITHUB_CLIENT_ID_LOGIN=
      # - GITHUB_CLIENT_SECRET_LOGIN=
      # - GITHUB_CLIENT_ID_LINK=
      # - GITHUB_CLIENT_SECRET_LINK=
      - GIT_REPO_SSH_URL=git@framagit.org:aloes/device-manager.git
      - INSTANCES_COUNT=1
    build:
      context: .
      dockerfile: ./config/docker/test.dockerfile
    ports:
      - '8000:8000'
      - '1883:1883'
    expose:
      - 8000
      - 1883
    depends_on:
      - influxdb
    links:
      - influxdb

volumes:
  influxvolume:

