version: '3.7'

services:
  influxdb:
    env_file: ./config/influx/.env
    image: influxdb:1.7-alpine
    volumes:
      - influxvolume:/var/lib/influxdb

  api:
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=4
      # - CI=true
    build:
      context: .
      dockerfile: ./config/docker/test.dockerfile
    expose:
      - '${HTTP_SERVER_PORT}'
      - '${MQTT_BROKER_PORT}'
    depends_on:
      - influxdb
    links:
      - influxdb
    volumes:
      - ./.env:/home/node/device-manager/.env:ro

  api-proxy:
    environment:
      - WS_BROKER_PORT=${WS_BROKER_PORT}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - NGINX_HTTP_SERVER_PORT=80
      - NGINX_HTTP_SERVER_HOST=${DOMAIN}
    image: nginx:1.16
    restart: always
    depends_on:
      - api
    links:
      - api
    ports:
      - '80:80'
      - '${MQTT_BROKER_PORT}:${MQTT_BROKER_PORT}'
    expose:
      - 80
      - ${MQTT_BROKER_PORT}
    volumes:
      - ./config/nginx/nginx-test.template:/etc/nginx/nginx.template
      - ./log/nginx:/etc/nginx/log
    command: /bin/bash -c "envsubst '$${HTTP_SERVER_PORT},$${WS_BROKER_PORT},$${MQTT_BROKER_PORT},$${NGINX_HTTP_SERVER_PORT},$${NGINX_HTTP_SERVER_HOST}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
  influxvolume:

