# Copyright 2019 Edouard Maleix, read LICENSE

version: '3.7'

networks:
  skyring:
    driver: bridge
  aloes:
    driver: bridge

services:
  mongo:
    env_file: ./config/mongo/.env
    image: mongo:4.1.13
    restart: always
    volumes:
      - ./config/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongovolume:/data/db
    networks:
      - aloes

  influxdb:
    env_file: ./config/influx/.env
    image: influxdb:1.7-alpine
    restart: always
    volumes:
      - influxvolume:/var/lib/influxdb
    networks:
      - aloes

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redisvolume:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - aloes
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

  timer-1:
    build:
      context: https://github.com/esatterwhite/skyring.git#master
    hostname: timer-1
    environment:
      - DEBUG=*
      - channel__host=timer-1
      - nats__hosts=nats-a:4222,nats-b:4222,nats-c:4222
      - seeds=timer-1:3455,timer-2:3456
      - storage__backend=leveldown
      - storage__path=/var/data/skyring
    image: aloes/timer-api:latest
    restart: always
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  timer-2:
    build:
      context: https://github.com/esatterwhite/skyring.git#master
    hostname: timer-2
    environment:
      - DEBUG=*
      - channel__host=timer-2
      - channel__port=3456
      - nats__hosts=nats-a:4222,nats-b:4222,nats-c:4222
      - seeds=timer-1:3455,timer-2:3456
      - storage__backend=leveldown
      - storage__path=/var/data/skyring
    image: aloes/timer-api:latest
    restart: always
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c

  timer-3:
    build:
      context: https://github.com/esatterwhite/skyring.git#master
    hostname: timer-3
    environment:
      - DEBUG=*
      - channel__host=timer-3
      - nats__hosts=nats-a:4222,nats-b:4222,nats-c:4222
      - seeds=timer-1:3455,timer-2:3456
      - storage__backend=leveldown
      - storage__path=/var/data/skyring
    image: aloes/timer-api:latest
    restart: always
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - timer-1
      - timer-2

  timer-4:
    build:
      context: https://github.com/esatterwhite/skyring.git#master
    hostname: timer-4
    environment:
      - DEBUG=*
      - channel__host=timer-4
      - nats__hosts=nats-a:4222,nats-b:4222,nats-c:4222
      - seeds=timer-1:3455,timer-2:3456
      - storage__backend=leveldown
      - storage__path=/var/data/skyring
    image: aloes/timer-api:latest
    restart: always
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - timer-1
      - timer-2

  timer-5:
    build:
      context: https://github.com/esatterwhite/skyring.git#master
    hostname: timer-5
    environment:
      - DEBUG=*
      - channel__host=timer-5
      - nats__hosts=nats-a:4222,nats-b:4222,nats-c:4222
      - seeds=timer-1:3455,timer-2:3456
      - storage__backend=leveldown
      - storage__path=/var/data/skyring
    image: aloes/timer-api:latest
    restart: always
    networks:
      - skyring
    depends_on:
      - nats-a
      - nats-b
      - nats-c
      - timer-1
      - timer-2
      - timer-3
      - timer-4

  nats-a:
    image: nats:latest
    volumes:
      - ./config/nats:/tmp
    restart: always
    networks:
      - skyring
    command: >
      -c /tmp/a.conf -D

  nats-b:
    image: nats:latest
    volumes:
      - ./config/nats:/tmp
    depends_on:
      - nats-a
    restart: always
    networks:
      - skyring
    command: >
      -c /tmp/b.conf -D

  nats-c:
    image: nats:latest
    volumes:
      - ./config/nats:/tmp
    restart: always
    depends_on:
      - nats-a
    networks:
      - skyring
    command: >
      -c /tmp/c.conf -D

  timer-proxy:
    image: nginx:latest
    volumes:
      - ./config/nginx/skyring.conf:/etc/nginx/nginx.conf
    restart: always
    networks:
      - skyring
    depends_on:
      - timer-1
      - timer-2
      - timer-3
      - timer-4
      - timer-5

  mqtt-api-1:
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=3
    build:
      context: .
      dockerfile: ./config/docker/broker.dockerfile
    image: aloes/mqtt-api:latest
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
    restart: always
    depends_on:
      - redis
    networks:
      - aloes

  mqtt-api-2:
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=3
    build:
      context: .
      dockerfile: ./config/docker/broker.dockerfile
    image: aloes/mqtt-api:latest
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
    restart: always
    depends_on:
      - redis
      - mqtt-api-1
    networks:
      - aloes

  http-api-1:
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=4
      - INSTANCES_COUNT=2
      - INSTANCES_PREFIX=1
    build:
      context: .
      dockerfile: ./config/docker/server.dockerfile
    image: aloes/http-api:latest
    restart: always
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
      - apivolume:/home/node/device-manager/storage
    depends_on:
      - mongo
      - influxdb
      - redis
      - timer-proxy
      - mqtt-api-1
      - mqtt-api-2
    networks:
      - aloes

  http-api-2:
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=4
      - INSTANCES_COUNT=2
      - INSTANCES_PREFIX=2
    build:
      context: .
      dockerfile: ./config/docker/server.dockerfile
    image: aloes/http-api:latest
    restart: always
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
      - apivolume:/home/node/device-manager/storage
    depends_on:
      - mongo
      - influxdb
      - redis
      - timer-proxy
      - mqtt-api-1
      - mqtt-api-2
      - http-api-1
    networks:
      - aloes

  http-api-3:
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=4
      - INSTANCES_COUNT=2
      - INSTANCES_PREFIX=3
    build:
      context: .
      dockerfile: ./config/docker/server.dockerfile
    image: aloes/http-api:latest
    restart: always
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
      - apivolume:/home/node/device-manager/storage
    depends_on:
      - mongo
      - influxdb
      - redis
      - timer-proxy
      - mqtt-api-1
      - mqtt-api-2
      - http-api-1
      - http-api-2
    networks:
      - aloes

  api-proxy:
    environment:
      - WS_BROKER_PORT=${WS_BROKER_PORT}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - NGINX_SERVER_HOST=${DOMAIN}
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx/nginx-local.template:/etc/nginx/nginx.template
      - ./log/nginx:/etc/nginx/log
    depends_on:
      - mqtt-api-1
      - mqtt-api-2
      - http-api-1
      - http-api-2
      - http-api-3
      - timer-proxy
    ports:
      - '80:80'
      - '1883:1883'
    networks:
      - aloes
      - skyring
    command: /bin/bash -c "envsubst '$${HTTP_SERVER_PORT},$${WS_BROKER_PORT},$${MQTT_BROKER_PORT},$${NGINX_SERVER_HOST}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
  mongovolume:
  redisvolume:
  influxvolume:
  apivolume:
