# Copyright 2020 Edouard Maleix, read LICENSE

version: '3.7'

networks:
  aloes:
    driver: bridge

services:
  mongo:
    env_file: ./config/mongo/.env
    image: mongo:4.1.13
    restart: always
    volumes:
      - ./config/mongo/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh:ro
      - mongovolume:/data/db
    networks:
      - aloes

  influxdb:
    env_file: ./config/influx/.env
    image: influxdb:1.7-alpine
    restart: always
    volumes:
      - influxvolume:/var/lib/influxdb
    networks:
      - aloes

  redis:
    image: redis:5-alpine
    restart: always
    volumes:
      - redisvolume:/data
      - ./config/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - aloes
    command: ['redis-server', '/usr/local/etc/redis/redis.conf']

  timer-1:
    image: quay.io/esatterwhite/skyring
    hostname: timer-1
    environment:
      - DEBUG=*
      - channel__host=timer-1
      - nats__hosts=nats-a:4222
      - seeds=timer-1:3455
      - storage__backend=leveldown
      - storage__path=/var/data/skyring
    restart: always
    depends_on:
      - nats-a
    networks:
      - aloes

  nats-a:
    image: nats:latest
    restart: always
    networks:
      - aloes

  async-api-1:
    image: getlarge/aloes-async-api:staging
    container_name: async-api-1
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=4
    restart: always
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
      - ./deploy/key.pem:/home/node/device-manager/deploy/key.pem
      - ./deploy/cert.pem:/home/node/device-manager/deploy/cert.pem
    depends_on:
      - redis
    networks:
      - aloes
    
  rest-api-1:
    image: getlarge/aloes-rest-api:staging
    container_name: rest-api-1
    env_file: .env
    environment:
      - SERVER_LOGGER_LEVEL=4
      - INSTANCES_COUNT=2
      - INSTANCES_PREFIX=1
    restart: always
    volumes:
      - ./.env:/home/node/device-manager/.env:ro
      - apivolume:/home/node/device-manager/storage
      - ./deploy/key.pem:/home/node/device-manager/deploy/key.pem
      - ./deploy/cert.pem:/home/node/device-manager/deploy/cert.pem
    depends_on:
      - mongo
      - influxdb
      - redis
      - timer-1
      - async-api-1
    networks:
      - aloes

  api-proxy:
    environment:
      - WS_BROKER_PORT=${WS_BROKER_PORT}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT}
      - HTTP_SERVER_PORT=${HTTP_SERVER_PORT}
      - NGINX_SERVER_HOST=${DOMAIN}
    image: nginx:latest
    restart: always
    volumes:
      - ./config/nginx/nginx-production.template:/etc/nginx/nginx.template
      - ./deploy/key.pem:/etc/nginx/certs/${DOMAIN}/key.pem
      - ./deploy/cert.pem:/etc/nginx/certs/${DOMAIN}/cert.pem
      - ./deploy/dhparam.pem:/etc/nginx/certs/dhparam.pem
      - ./log/nginx:/etc/nginx/log
    depends_on:
      - mqtt-api-1
      - http-api-1
      - timer-1
    ports:
      - '80:80'
      - '443:443'
      - '1883:1883'
      - '8883:8883'
    networks:
      - aloes
    command: /bin/bash -c "envsubst '$${HTTP_SERVER_PORT},$${WS_BROKER_PORT},$${MQTT_BROKER_PORT},$${NGINX_SERVER_HOST}' < /etc/nginx/nginx.template > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

volumes:
  mongovolume:
  redisvolume:
  influxvolume:
  apivolume:
