/* Copyright 2020 Edouard Maleix, read LICENSE */

module.exports = {
  local: {
    provider: 'local',
    module: 'passport-local',
    usernameField: 'email',
    passwordField: 'password',
    domain: process.env.DOMAIN,
    authPath: `${process.env.REST_API_ROOT}/auth/login`,
    // authPath: `${process.env.REST_API_ROOT}/${process.env.REST_API_VERSION}/auth/login`,
    //    callbackPath: `/api/auth/login`,
    //    successRedirect: '/auth/account',
    //     failureRedirect: '/local',
    successRedirect: `${process.env.HTTP_CLIENT_URL}/auth`,
    failureRedirect: `${process.env.HTTP_CLIENT_URL}/login`,
    json: true,
    setAccessToken: true,
    failureFlash: true,
    successFlash: true,
  },
  'github-login': {
    provider: 'github',
    module: 'passport-github',
    strategy: 'OAuth2Strategy',
    domain: process.env.DOMAIN,
    clientID: process.env.GITHUB_CLIENT_ID_LOGIN,
    clientSecret: process.env.GITHUB_CLIENT_SECRET_LOGIN,
    callbackURL: `${process.env.HTTP_SERVER_URL}/auth/github/callback`,
    // callbackURL: `${process.env.HTTP_SERVER_URL}/${process.env.REST_API_ROOT}/${process.env.REST_API_VERSION}/auth/github/callback`,
    authPath: `${process.env.REST_API_ROOT}/auth/github`,
    // authPath: `${process.env.REST_API_ROOT}/${process.env.REST_API_VERSION}/auth/github`,
    callbackPath: `/auth/github/callback`,
    successRedirect: `${process.env.HTTP_CLIENT_URL}/auth`,
    successFlash: true,
    failureRedirect: `${process.env.HTTP_CLIENT_URL}/login`,
    failureQueryString: true,
    failureFlash: true,
    scope: ['email'],
    session: true,
    json: false,
    profileFields: ['id', 'displayName', 'username', 'profileUrl', 'email'],
  },
  'github-link': {
    provider: 'github',
    module: 'passport-github',
    strategy: 'OAuth2Strategy',
    clientID: process.env.GITHUB_CLIENT_ID_LINK,
    clientSecret: process.env.GITHUB_CLIENT_SECRET_LINK,
    callbackURL: `${process.env.HTTP_SERVER_URL}/link/github/callback`,
    authPath: `${process.env.REST_API_ROOT}/link/github`,
    // authPath: `${process.env.REST_API_ROOT}/${process.env.REST_API_VERSION}/link/github`,
    callbackPath: `/link/github/callback`,
    successRedirect: `${process.env.HTTP_CLIENT_URL}/auth`,
    successFlash: true,
    failureRedirect: `${process.env.HTTP_CLIENT_URL}/login`,
    failureQueryString: true,
    failureFlash: false,
    scope: ['email', 'profile'],
    profileFields: ['id', 'displayName', 'username', 'profileUrl', 'email'],
    //    session: false,
    link: true,
  },
};
